### ISSUE TITLE
arangodb alert rules

### ISSUE THREAD

**Issue by neha-kapila94** [arangodb-helper/arangodb-exporter#28]
It would be nice to have some example rules we could use to create alerts. Check out https://awesome-prometheus-alerts.grep.to/rules.html for some examples of rules from other exporter tools.

**Comment by dothebart** [comment]
Hi, 
please note that this is deprecated and ArangoDB meanwhile directly exposes prometheus gauges. 

Please see
https://www.arangodb.com/docs/stable/http/monitoring.html#metrics-api-v2
for the details.

**Comment by Luschgy** [comment]
won't fix
